highligher: rogue
name: Geoffrey Lovelace
url: "http://geoffrey-lovelace.com"
lsi: false
theme: jekyll-theme-midnight
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
permalink: pretty
