highligher: rogue
name: Geoffrey Lovelace
url: "http://geoffrey-lovelace.com"
description: "Associate Professor of Physics at California State University, Fullerton"
title: Geoffrey Lovelace
lsi: false
theme: jekyll-theme-midnight
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
permalink: pretty
plugins: 
- jekyll-menus
